const notFoundError = (res, message={error: "Recurso nÃ£o encontrado"}) => {
    return res.status(404).send(message);
}

export default notFoundError;